apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/amberin/argo-labb
    path: cluster-infra-apps/argo-cd
  destination:
    name: "in-cluster"
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
